# MicroProfile LRA demo: DevConf 2019.cz

# Quickie...

* `docker run -p 8080:8080 docker.io/ochaloup/lra-coordinator:devconf2019`
* `docker run -e TARGET_CALL='http://localhost:8888' -p 8180:8080 docker.io/ochaloup/devconf2019`

# notes

* to access docker to localhots: `--add-host="localhost:192.168.65.1"`
* `java -jar target/devconf2019-flightbooking-thorntail.jar -Dthorntail.http.port=8180 -Dtarget.call=http://localhost:8888 -Dlra.http.host=localhost -Dlra.http.port=8080 -Dswarm.bind.address=10.200.138.81`

This is a small demo project which shows
basic capabilities of MicroProfile Long Running Action.
That's specification based on the Saga pattern
which is designed to provide transactional guarantees
for microservice architecture.

The LRA is based on HTTP-REST communication.
It expects a LRA HTTP coordination endpoints to be available.
In case of http://narayana.io[Narayana] implementation of the specification
there is provided a LRA coordinator which manages the LRA lifecicle.
Application enlists itself to the coordinator while
exposing REST endpoints. The LRA coordinator uses those application's endpoints
to inform about outcome of the LRA processing.

Some more information about Narayana LRA processing could be found at article
http://jbossts.blogspot.com/2017/12/narayana-lra-implementation-of-saga.html

## How to run

### LRA API compilation

The https://github.com/eclipse/microprofile-lra[LRA specification] is not a finalized (January 2019).
 The CR releases for testing are hopefully near from now. But for testing is necessary to build
 snapshot in current days.

* `git clone https://github.com/eclipse/microprofile-lra`
* `cd microprofile-lra`
* `mvn clean install`


### Starting Narayana LRA coordinator

As the LRA specification is only in a draft state there could be cases that is necessary
to run the Narayana LRA coordinator as `SNAPSHOT` too. In such case you need to compile
Narayana project in way

* `git clone https://github.com/jbosstm/narayana.git`
* `cd narayana`
* `mvn clean install -DskipTests`
* `java -jar rts/lra/lra-coordinator/target/lra-coordinator-swarm.jar -Dswarm.http.port=8180`

Otherwise the easiest way is to use the docker to run the coordinator
(coordinator is under dockerhub at https://hub.docker.com/r/jbosstm/lra-coordinator).

* `docker run -p 8080:8080 jbosstm/lra-coordinator`

To run coordinator with showing `debug`/`trace` messages run with
`-Dswarm.logging=DEBUG` in case of `java -jar` command or
set environment variable `-e LOG_LEVEL="DEBUG"`.


### Running this demo

When LRA API is installed as maven dependency to local mvn repository
and the coordinator is running you can run this demo app.
The demo application starts as a Thorntail application which exposes
several endpoints 

* `git clone https://github.com/ochaloup/devconf2019-lra.git`
* `cd devconf2019-lra`
* `mvn package`
* `java -jar target/devconf2019-flightbooking-thorntail.jar -Dinit.csv=./flight.data -Dlra.http.host=localhost -Dlra.http.port=8180`

NOTE: the `flight.data` is csv file of format `date<yyyy-MM-dd>;seats;seatsBooked`
      and those data is loaded during app startup

#### Using REST endpoints for Flight

`curl -D -i -XGET http://localhost:8080/flights/all | jq`::
  show all available flights
`curl -D -i -XGET http://localhost:8080/flights/2 | jq`::
  get flight entity searched by its id
`curl -i --header "Content-Type: application/json" -XPOST http://localhost:8080/flights/add --data '{"date":"2018-01-31", "numberOfSeats":100, "bookedSeats": 99}'`::
  adding new flight to database
`curl -i -XDELETE http://localhost:8080/flights/2`::
  delete the flight from database
`curl -i -XGET http://localhost:8080/flights/date/2018-01-03`::
  searching for flight by a date

#### Using REST endpoints for Booking

`curl -i --header "Content-Type: application/json" -XPOST http://localhost:8080/book --data '{"date":"2018-01-01", "name": "Franta Vomacka"}'`::
  book a flight
`curl -i -XGET http://localhost:8080/book/all`::
  get all bookings


## Communicating with coordinator with `curl` commands

NOTE: expecting the coordinator is started at port `8180`. Either with docker `-p 8180:8080`
      or by WildFly Swarm port definition `swarm.http.port`

To get coordinoator API you can download Swagger JSON by calling
http://localhost:8080/swagger.json
Or you can ckeck  
https://raw.githubusercontent.com/ochaloup/narayana/swagger-json/rts/lra/lra-coordinator/swagger.json[https://github.com/ochaloup/narayana/blob/swagger-json/rts/lra/lra-coordinator/swagger.json]
for some older version of the API represented by the Swagger JSON.

[NOTE]
====
For verification that there is sent data back from coordinator to client service
you can use some simple HTTP server showing what it gets. For example `http-echo-server`.

```
npm install http-echo-server -g
PORT=8081 http-echo-server
```

====

### Starting LRA

`curl -i -XPOST http://localhost:8080/lra-coordinator/start?clientID=1`

will return the LRA ID as body of the response. It's in form of URI.
It could be for example `http://localhost:8080/lra-coordinator/0_ffffac110002_-1c1af658_5c45b21d_41`.

### List All active LRAs

`curl -i -XGET http://localhost:8080/lra-coordinator/`

### Enlisting a participant microservice to LRA

`curl -i -XPUT http://localhost:8080/lra-coordinator/0_ffffac110002_-23367453_5c45d7d0_11 --data "http://localhost:8081"`

which will enlist participant at path `http://localhost:8081` expecting the participant exposes
endpoinds `/compensate`, `/complete` and `/status`.

Or you can define the endpoints particularly by using `Link` header.

```
curl -i -XPUT  http://localhost:8080/lra-coordinator/0_ffff0a000002_7009eb01_5c463d32_f \
  -H 'Link:<http://localhost:8081/leave-linkh>; rel="leave"; title="leave URI"; type="text/plain",<http://localhost:8081/complete-linkh>; rel="complete"; title="complete URI"; type="text/plain",<http://localhost:8081/compensate-linkh>; rel="compensate"; title="compensate URI"'
```

The `complete`, `compensate` endpoints is expected to listen to `PUT` requests. The coordinator provides HTTP header `Long-Running-Action`
which contains the LRA id that can be used by the participant for the purpose it needs.
If participants provide some data in body during the `enlist` call then this data will be returned in body
on the call of `compensate` and `complete`.

To call finish the LRA you can use call either to `close` which informs the coordinator to finish LRA with success (aka. all participants will be called on `complete` endpoint), or you can call cancel
which informs about LRA failure (aka. all participants will be called on `compensate` endpoint).

* `curl -i -XPUT http://localhost:8080/lra-coordinator/0_ffff0a000002_7009eb01_5c463d32_22/close`
* `curl -i -XPUT http://localhost:8080/lra-coordinator/0_ffff0a000002_7009eb01_5c463d32_22/cancel`

To find out status of LRA use `/status` `GET` call to coordinator like

`curl -i -XGET http://localhost:8080/lra-coordinator/0_ffff0a000002_7009eb01_5c463d32_22/status`

